export const projects = [
    {
      name: "Traditional Instruments",
      imgSrc: "/aset/Tr.jpg",
      Url: "https://github.com/linvxcode/traditional-instrument-web",
      content:
        "I created a website for learning and practicing musical instruments",
      imgBuild: "/aset/laravel-min.png",
      svg2: "/svg/tailwind.svg",
      svg3: "/svg/jquery.svg",
      initial: { scale: 0.8 },
      whileInVIew: { scale: 1, transition: { type: "spring", duration: 2 } },
    },
    {
      name: "E-Warung",
      imgSrc: "/aset/6edit.jpg",
      Url: "https://github.com/linvxcode/e-warung",
      content: "I created an e-commerce website for shopping",
      imgBuild: "/aset/laravel-min.png",
      imgBuildTwo: "/aset/react-min.png",
      svg: "/svg/framer.svg",
      svg3: "/svg/tailwind.svg",
      initial: { scale: 0.8 },
      whileInVIew: { scale: 1, transition: { type: "spring", duration: 2 } },
    },
    {
      name: "Landing Page",
      imgSrc: "/aset/1edit.jpg",
      Url: "https://slicing-landing-page-theta.vercel.app/",
      content: "Frontend Slicing From Figma To React",
      imgBuild: "/aset/react-min.png",
      svg: "/svg/framer.svg",
      svg2:"/svg/tailwind.svg",
      initial: { scale: 0.8 },
      whileInVIew: { scale: 1, transition: { type: "spring", duration: 2 } },
    },
    {
      name: "Landing Page Portofolio",
      imgSrc: "/aset/3edit.jpg",
      Url: "https://portofolio-indra.vercel.app/",
      content: "Slicing Landing Page Portofolio From Figma To Next Js",
      imgBuild: "/aset/next.png",
      svg: "/svg/framer.svg",
      svg2: "/svg/tailwind.svg",
      initial: { scale: 0.8 },
      whileInVIew: { scale: 1, transition: { type: "spring", duration: 2 } },
    },
    {
      name: "Landing Page Portofolio",
      imgSrc: "/aset/4edit.jpg",
      Url: "https://portofolio-fahlevi.vercel.app/",
      content: "Personal Website Portofolio build with nextjs",
      imgBuild: "/aset/next.png",
      svg: "/svg/framer.svg",
      svg2: "/svg/tailwind.svg",
      initial: { scale: 0.8 },
      whileInVIew: { scale: 1, transition: { type: "spring", duration: 2 } },
    },
  ];