export const projects = [
    {
      name: "Traditional Instruments",
      imgSrc: "/aset/Tr.jpg",
      Url: "https://github.com/linvxcode/traditional-instrument-web",
      content:
        "I created a website for learning and practicing musical instruments",
      imgBuild: "/svg/laravel.svg",
      svg2: "/svg/tailwind.svg",
      svg3: "/svg/jquery.svg",
      initial: { scale: 0.9 },
      whileInVIew: { scale: 1, transition: { type: "spring", duration: 1 } },
    },
    {
      name: "E-Warung",
      imgSrc: "/aset/6edit.jpg",
      Url: "https://github.com/linvxcode/e-warung",
      content: "I created an e-commerce website for shopping",
      imgBuild: "/svg/laravel.svg",
      svg4: "/svg/react.svg",
      svg: "/svg/framer.svg",
      svg3: "/svg/tailwind.svg",
      initial: { scale: 0.9 },
      whileInVIew: { scale: 1, transition: { type: "spring", duration: 1 } },
    },
    {
      name: "Landing Page",
      imgSrc: "/aset/1edit.jpg",
      Url: "https://slicing-landing-page-theta.vercel.app/",
      content: "Frontend Slicing From Figma To React",
      svg4: "/svg/react.svg",
      svg: "/svg/framer.svg",
      svg2:"/svg/tailwind.svg",
      initial: { scale: 0.9 },
      whileInVIew: { scale: 1, transition: { type: "spring", duration: 1 } },
    },
    {
      name: "Landing Page Portofolio",
      imgSrc: "/aset/3edit.jpg",
      Url: "https://portofolio-indra.vercel.app/",
      content: "Slicing Landing Page Portofolio From Figma To Next Js",
      imgBuild: "/svg/next.svg",
      svg: "/svg/framer.svg",
      svg2: "/svg/tailwind.svg",
      initial: { scale: 0.9 },
      whileInVIew: { scale: 1, transition: { type: "spring", duration: 1 } },
    },
    {
      name: "Landing Page Portofolio",
      imgSrc: "/aset/4edit.jpg",
      Url: "https://portofolio-fahlevi.vercel.app/",
      content: "Personal Website Portofolio build with nextjs",
      imgBuild: "/svg/next.svg",
      svg: "/svg/framer.svg",
      svg2: "/svg/tailwind.svg",
      initial: { scale: 0.9 },
      whileInVIew: { scale: 1, transition: { type: "spring", duration: 1 } },
    },
  ];