export const projects = [
    {
      name: "Website Portofolio",
      imgSrc: "/aset/new-porto.jpg",
      Url: "https://personal-website-linvxcode.vercel.app/",
      content:
        "Personal Website portofolio was built with Next Js + Tailwind Css + Framer Motion",
      imgBuild: "/svg/next.svg",
      svg2: "/svg/tailwind.svg",
      svg3: "/svg/framer.svg",
      initial: { scale: 0.9 },
      whileInVIew: { scale: 1, transition: { type: "spring", duration: 1 } },
    },
    {
      name: "Traditional Instruments",
      imgSrc: "/aset/Tr.jpg",
      Url: "https://github.com/linvxcode/traditional-instrument-web",
      content:
        "website learning and practicing musical instruments was built with laravel + tailwind css",
      imgBuild: "/svg/laravel.svg",
      svg2: "/svg/tailwind.svg",
      svg3: "/svg/jquery.svg",
      initial: { scale: 0.9 },
      whileInVIew: { scale: 1, transition: { type: "spring", duration: 1 } },
    },
    {
      name: "E-Warung",
      imgSrc: "/aset/6edit.jpg",
      Url: "https://github.com/linvxcode/e-warung",
      content: "The e-warung website is a website that runs like e-commerce in general, which is a place to shop",
      imgBuild: "/svg/laravel.svg",
      svg4: "/svg/react.svg",
      svg: "/svg/framer.svg",
      svg3: "/svg/tailwind.svg",
      initial: { scale: 0.9 },
      whileInVIew: { scale: 1, transition: { type: "spring", duration: 1 } },
    },
    {
      name: "Landing Page",
      imgSrc: "/aset/1edit.jpg",
      Url: "https://slicing-landing-page-theta.vercel.app/",
      content: "Slicing Simple modern Design Frontend From Figma To React with framer motion and tailwind css",
      svg4: "/svg/react.svg",
      svg: "/svg/framer.svg",
      svg2:"/svg/tailwind.svg",
      initial: { scale: 0.9 },
      whileInVIew: { scale: 1, transition: { type: "spring", duration: 1 } },
    },
    {
      name: "Landing Page Portofolio",
      imgSrc: "/aset/3edit.jpg",
      Url: "https://portofolio-indra.vercel.app/",
      content: "Slicing Landing Page Portofolio From Figma To Next Js with framer motion and tailwind css",
      imgBuild: "/svg/next.svg",
      svg: "/svg/framer.svg",
      svg2: "/svg/tailwind.svg",
      initial: { scale: 0.9 },
      whileInVIew: { scale: 1, transition: { type: "spring", duration: 1 } },
    },
    {
      name: "Landing Page Portofolio",
      imgSrc: "/aset/4edit.jpg",
      Url: "https://portofolio-fahlevi.vercel.app/",
      content: "Personal Website Portofolio build with nextjs with framer motion and tailwind css",
      imgBuild: "/svg/next.svg",
      svg: "/svg/framer.svg",
      svg2: "/svg/tailwind.svg",
      initial: { scale: 0.9 },
      whileInVIew: { scale: 1, transition: { type: "spring", duration: 1 } },
    },
    {
      name: "Landing Page Portofolio",
      imgSrc: "/aset/sport.jpg",
      Url: "https://sport-linvxcode.vercel.app/",
      content: "Slicing Landing Page Portofolio From Figma To Next Js with framer motion and tailwind css",
      imgBuild: "/svg/next.svg",
      svg: "/svg/framer.svg",
      svg2: "/svg/ts.svg",
      initial: { scale: 0.9 },
      whileInVIew: { scale: 1, transition: { type: "spring", duration: 1 } },
    },
  ];